### ISSUE TITLE
Plugin No Longer Works

### ISSUE THREAD

**Issue by bolderelements** [pippinsplugins/bbPress-Export-and-Import#2]
The export does not seem to work. When I opened my export files in excel, this is what I was created with:

post_type;"post_author";"user_login";"post_parent";"post_content";"post_title";"post_date_gmt";"post_date";"anonymous";"voices";"reply_count";"resolved"
<br />
<b>Notice</b>:  Undefined variable: data in <b>/home/eridio1/bolderelements.net/wp-content/plugins/bbPress-Export-and-Import-master/includes/export.php</b> on line <b>202</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/home/eridio1/bolderelements.net/wp-content/plugins/bbPress-Export-and-Import-master/includes/export.php</b> on line <b>220</b><br />

**Comment by bolderelements** [comment]
Ugh, never mind. I guess it doesn't work on categories, just each individual forum. That is disappointing but as its the only one on the market that actually works (just requires extra work) thank you!

Just a note though, it only moves active published posts. Since I use this as an archive as well (closed topics) I would recommend adding the following code to the function on Line 128

'post_status' => 'any',

**Comment by pippinsplugins** [comment]
I'll look into tweaking that, thanks for the catch!
